# Generated by Django 2.1.5 on 2019-01-19 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(blank=True, max_length=15)),
                ('branch', models.CharField(choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], max_length=15)),
                ('checkin', models.BooleanField(default=False)),
                ('seat_no', models.CharField(blank=True, max_length=15, null=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Attendees',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('branch', models.CharField(choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], max_length=15)),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_3', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('slot_4', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('slot_5', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('slot_6', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('slot_7', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('slot_8', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('slot_9', models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15)),
                ('total_seats_1', models.IntegerField(blank=True, default=0)),
                ('total_seats_2', models.IntegerField(blank=True, default=0)),
                ('total_seats_3', models.IntegerField(blank=True, default=0)),
                ('vacant_seats_1', models.IntegerField(blank=True, default=0)),
                ('vacant_seats_2', models.IntegerField(blank=True, default=0)),
                ('vacant_seats_3', models.IntegerField(blank=True, default=0)),
                ('reserved', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
