# Generated by Django 2.1.5 on 2019-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_1',
            field=models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='slots',
            name='slot_2',
            field=models.CharField(blank=True, choices=[('INFT', 'Information Tech.'), ('CMPN', 'Computer Science'), ('ETRX', 'Electronics'), ('EXTC', 'Electronics & Tele.'), ('BIOM', 'Biomedical'), ('MMS', 'Management Studies')], default=None, max_length=15),
        ),
    ]
