# Generated by Django 2.1.5 on 2019-01-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_auto_20190119_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
