# Generated by Django 2.1.5 on 2019-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_auto_20190119_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='seat_no_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slots',
            name='seat_no_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slots',
            name='seat_no_3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
