# Generated by Django 2.1.5 on 2019-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0007_auto_20190120_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='seat_no_1',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='seat_no_2',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='seat_no_3',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='vacant_seats_1',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='vacant_seats_2',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='vacant_seats_3',
        ),
        migrations.AddField(
            model_name='slots',
            name='occupied_seats_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slots',
            name='occupied_seats_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slots',
            name='occupied_seats_3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
