# Generated by Django 2.1.5 on 2019-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0009_auto_20190120_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='value_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slots',
            name='value_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slots',
            name='value_3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
