# Generated by Django 2.1.5 on 2019-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0010_auto_20190120_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='value_1',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='value_2',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='value_3',
        ),
        migrations.AddField(
            model_name='slots',
            name='update_choice',
            field=models.IntegerField(default=0),
        ),
    ]
